using AiSdk.Abstractions;

namespace AiSdk.Models;

/// <summary>
/// Result of generating a structured object from a language model.
/// </summary>
/// <typeparam name="T">The type of the generated object.</typeparam>
public record GenerateObjectResult<T>
{
    /// <summary>
    /// The generated object.
    /// </summary>
    public required T Object { get; init; }

    /// <summary>
    /// The raw text generated by the model before parsing.
    /// </summary>
    public string? RawText { get; init; }

    /// <summary>
    /// The reason why generation finished.
    /// </summary>
    public FinishReason? FinishReason { get; init; }

    /// <summary>
    /// Token usage statistics for this generation.
    /// </summary>
    public Usage? Usage { get; init; }

    /// <summary>
    /// Any warnings encountered during generation or parsing.
    /// </summary>
    public IReadOnlyList<string>? Warnings { get; init; }
}
